/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./JunoNftMarketplaceX.types";
import * as _1 from "./JunoNftMarketplaceX.client";
import * as _2 from "./JunoNftMarketplaceX.message-composer";
import * as _3 from "./JunoNftMarketplaceX.react-query";
export namespace contracts {
  export const JunoNftMarketplaceX = {
    ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}