/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw1155x.types";
import * as _1 from "./Cw1155x.client";
import * as _2 from "./Cw1155x.message-composer";
import * as _3 from "./Cw1155x.react-query";
import * as _4 from "./Cw1155x.recoil";
export namespace tta {
  export const Cw1155x = {
    ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
}