/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./JunoMarketplace.types";
import * as _1 from "./JunoMarketplace.client";
import * as _2 from "./JunoMarketplace.react-query";
export namespace contracts {
  export const JunoMarketplace = {
    ..._0,
    ..._1,
    ..._2
  };
}