/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { JMarketplaceClient, JMarketplaceQueryClient } from "./JMarketplace.client";
import { JMarketplaceMsgComposer } from "./JMarketplace.message-composer";
export class JMarketplace extends ContractBase<JMarketplaceClient, JMarketplaceQueryClient, JMarketplaceMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, JMarketplaceClient, JMarketplaceQueryClient, JMarketplaceMsgComposer);
  }
}